name: mobile_tixup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  iconsax_flutter: ^1.0.0
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  mask_text_input_formatter: ^2.4.0
  provider: ^6.1.1
  flip_card: ^0.7.0
  ionicons: ^0.2.2
  url_launcher: ^6.3.1
  image_picker: ^0.8.5+3
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/cards/visa.png
    - lib/assets/cards/mastercard.png
    - lib/assets/cards/amex.png
    - lib/assets/cards/discover.png
